
services:
  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: listi_ng
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
    - "3306:3306"
    volumes:
    - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
