version: '3.8'
services:
  mariadb:
    image: mariadb:11
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: examplepassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    ports:
    - "3306:3306"
    volumes:
    - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
