name: CI
on:
  push:
    branches:
      - master

permissions:
  actions: read
  contents: read
  id-token: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Authenticate with Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Make backend ci script executable
        run: chmod +x ./ci/scripts/build.sh

      - name: Make frontend ci script executable
        run: chmod +x ./ci/scripts/actions-front.sh

      - name: Configure Kubectl
        uses: azure/setup-kubectl@v3
        id: install-kubectl
        with:
          version: 'latest'

      - name: Authenticate to AKS cluster
        run: |
          az aks get-credentials --resource-group <RESOURCE_GROUP_NAME> --name <AKS_CLUSTER_NAME>

      - name: Show Base and Head SHAs
        run: |
          echo "Base SHA: ${{ github.sha }}~1"
          echo "Head SHA: ${{ github.sha }}"

      - name: Configure Docker for Azure Container Registry
        run: |
          az acr login --name <ACR_NAME>

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Get branch name (pull request)
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
        id: 'BRANCH'

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            **/.eslintcache
          key: ${{ runner.os }}-build_stage-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-build_stage-${{ env.cache-name }}-${{ runner.os }}-build-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci

      - run: npx nx affected -t docker-push bucket-push --base=${{ steps.BRANCH.outputs.branch }}~1 --head=${{ steps.BRANCH.outputs.branch }} --no-cloud
        env:
          NX_HEAD: ${{ github.sha }}
          BRANCH: ${{ steps.BRANCH.outputs.branch }}  